[package]
name = "reveal-yaml"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
description = "A YAML project manager serving Reveal.js slides."

[[bin]]
name = "rym"
path = "src/main.rs"

[dependencies]
clap = "2.33"
actix-web = "*"
markdown = "*"
latex2mathml = "*"
serde = "*"
serde_yaml = "*"
