[package]
name = "reveal-yaml"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
description = "A YAML project manager serving Reveal.js slides."

[[bin]]
name = "rym"
path = "src/main.rs"

[dependencies]
clap = "2.33"
temp-dir = "0.1"
zip = "0.5"
actix-web = "3.3"
actix-files = "0.5"
walkdir = "2.3"
serde = "*"
serde_yaml = "*"
markdown = "*"
latex2mathml = "*"

[dependencies.reqwest]
version = "0.11"
features = ["blocking"]
