[package]
name = "reveal-yaml"
description = "A YAML project manager serving Reveal.js slides."
version = "0.14.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/KmolYuan/reveal-yaml-rs"
readme = "README.md"
keywords = ["yaml", "revealjs", "reveal", "slide", "slideshow"]
categories = ["command-line-interface"]

[dependencies]
clap = "2.33"
temp-dir = "0.1"
zip = "0.5"
reqwest = { version = "0.11", features = ["blocking"] }
actix-web = "3.3"
actix-files = "0.5"
yaml-peg = { version = "0.20", features = ["serde-std"] }
pulldown-cmark = "0.8"
