[package]
name = "reveal-yaml-rs"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
markdown = "*"
latex2mathml = "*"
serde = "*"
serde_yaml = "*"
