[package]
name = "reveal-yaml"
description = "A YAML project manager serving Reveal.js slides."
version = "0.17.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/KmolYuan/reveal-yaml-rs"
readme = "README.md"
keywords = ["yaml", "revealjs", "reveal", "slide", "slideshow"]
categories = ["command-line-interface"]

[dependencies]
clap = { version = "3", features = ["derive"] }
yaml-peg = { version = "0.25", features = ["serde-std"] }
serde = { version = "1", features = ["derive"] }
temp-dir = "0.1"
zip = "0.5"
reqwest = "0.11"
actix = "0.12"
actix-web = "4.0.0-beta"
actix-web-actors = "4.0.0-beta"
actix-files = "0.6.0-beta"
webbrowser = "0.5"
pulldown-cmark = "0.9"
