name: Github Deploy
on:
  push:
    tags: [ v* ]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rym
            asset_name: reveal-yaml-linux-amd64
          - os: macOS-latest
            artifact_name: rym
            asset_name: reveal-yaml-macos-amd64
          - os: windows-latest
            artifact_name: rym.exe
            asset_name: reveal-yaml-windows-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - shell: bash
        run: |
          cargo build --all-features --release
      - name: Pack binaries
        uses: papeloto/action-zip@v1
        with:
          files: target/release/${{ matrix.artifact_name }}
          dest: ${{ matrix.asset_name }}.zip
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          files: ${{ matrix.asset_name }}.zip
          body: Automatically published from Github Actions.
